FROM golang:1.16

EXPOSE 3000

WORKDIR /indexer

ARG LOG_DIR=./logs
ARG CONFIG_DIR=./configs

RUN mkdir -p $LOG_DIR
RUN mkdir -p $CONFIG_DIR

COPY ./app/configs/config.yml $CONFIG_DIR

COPY ./app/go.mod ./
COPY ./app/go.sum ./

RUN go mod download

COPY ./app/main.go ./
COPY ./app/process/* ./process/
COPY ./app/model/* ./model/
COPY ./app/err/* ./err/
COPY ./app/handler/* ./handler/

RUN go install -v ./...

ENTRYPOINT ["/go/bin/altoindexer"]

