FROM golang:1.16

EXPOSE 3000

WORKDIR /processor

RUN groupadd -r user && useradd -r -g user user

ARG LOG_DIR=/var/log/ocr_processor
ARG FILE_DIR=/var/ocr_files
ARG CONFIG_DIR=./

RUN mkdir -p $LOG_DIR && chown -R user $LOG_DIR
RUN mkdir -p $FILE_DIR && chown -R user $FILE_DIR
RUN mkdir -p $CONFIG_DIR

COPY .app/assets/build/config.yml $CONFIG_DIR

COPY ./app/go.mod ./
COPY ./app/go.sum ./

RUN go mod download

COPY ./app/main.go ./
COPY ./app/process/* ./process/
COPY ./app/model/* ./model/
COPY ./app/err/* ./err/
COPY ./app/handler/* ./handler/

RUN go install -v ./...

USER user

ENTRYPOINT ["/go/bin/ocrprocessor"]

