dspace_host:
  "http://dspace.host.org:8080/server/api"
collections:
  - "2ea40294-9d27-4341-8476-4fb51732c213"
solr_url:
  "http://localhost:8983/solr"
solr_core:
  "word_highlighting"
xml_file_location:
  "/path/to/escaped_alto_files"
log_dir:
  "."
