http_port:
  # http port used by this service
  "3000"
# IP addresses of whitelisted hosts. If the list is empty, all IP's can access the service.
# Example: ["127.0.0.1", "192.168.0.1"]
ip_whitelist:
  []
dspace_host:
  # dspace api base (no trailing slash)
  "http://localhost:8080/server"
solr_url:
  # solr host (no trailing slash)
  "http://localhost:8983/solr"
solr_core:
  # the solr core name
  "word_highlighting"
file_format:
  # The application supports "alto" or "miniocr" formats
  "alto"
index_type:
  # You can use "lazy" or "full" indexing, see Solr OCR Highlighting documentation for details
  "lazy"
escape_utf8:
  # escape utf8 strings
  # when "lazy" loading ocr files from disk you can improve performance by converting utf8 to xml-encoded ascii strings.
  true
xml_file_location:
  # path used for lazy index files. Solr will read ocr files from this directory if "lazy" indexing is used.
  "/Users/mspalti/escaped_alto"

log_dir:
  "./logs"
