dspace_host:
  "http://localhost:8080/server/api"
collections:
  # unused
  - "2ea40294-9d27-4341-8476-4fb51732c213"
solr_url:
  "http://localhost:8983/solr"
solr_core:
  "word_highlighting"
xml_file_location:
  "/Users/michaelspalti/alto_transformed_solr"
http_port:
  "3000"
log_dir:
  # mount point for the container volume.
  "./logs"
